fix: flaky test `Test Snap Metrics test snap update rejected metric` (#25744)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**
The snap metrics test fails when trying to click the Confirm button,
since this is disabled, as we can see on the screenshot below. Despite
clicking scroll to bottom button successfully, we see how when we try to
click Confirm, we are back in the top of the screen, causing the button
to be disabled.

To fix this, we add a waitForSelector which makes sure that the content
of the permissions are there before clicking the scroll button. This
ensures that there is no re-render after clicking the scroll button,
avoiding being back on the top of the screen with the button disabled.

```
[driver] Called 'clickElement' with arguments [{"text":"Connect","tag":"button"}]
[driver] Called 'waitForSelector' with arguments [{"text":"Confirm"}]
[driver] Called 'clickElementSafe' with arguments ["[data-testid=\"snap-install-scroll\"]"]
[driver] Called 'clickElement' with arguments [{"text":"Confirm","tag":"button"}]
Failure on testcase: 'Test Snap Metrics test snap update rejected metric', for more information see the artifacts tab in CI

TimeoutError: Waiting until element is enabled
```

- Ci error
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/90862/workflows/6dbe2003-ac8e-4e35-9ad1-afab86e4b646/jobs/3374081/parallel-runs/9?filterBy=ALL

[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/25744?quickstart=1)

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-extension/issues/25746

## **Manual testing steps**

1. Check ci jobs

## **Screenshots/Recordings**

<!-- If applicable, add screenshots and/or recordings to visualize the
before and after of your change. -->


![image](https://github.com/MetaMask/metamask-extension/assets/54408225/299f9bbd-2037-4e03-b36e-3726e405b450)


## **Pre-merge author checklist**

- [x] I've followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask
Extension Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [x] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.