fix: fix flaky snap update e2e test in MV3 (#24908)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**

Captured in workflow of running e2e tests in chrome mv3 build, there's
an unstable test `Test Snap update can install an old and then updated
version`:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/83920/workflows/40fd32b8-474a-4cbc-b504-e1371d264ae0/jobs/3011910/tests

The error message is 
```
TimeoutError: Waiting for element to be located By(xpath, //*[contains(text(), "OK")])
Wait timed out after 10202ms
```
It is difficult to reproduce locally, but it is a clear fix from
[artifact](https://circleci-tasks-prod.s3.us-east-1.amazonaws.com/storage/artifacts/fb281712-ea41-446f-b28f-c0bea18842cc/fa51b9ed-ac64-4a60-b898-4415df7dd9b4/15/test-artifacts/chrome/Test%20Snap%20update%20can%20install%20an%20old%20and%20then%20updated%20version/test-failure-screenshot.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQVFQINEONI2BX3OH%2F20240530%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240530T144723Z&X-Amz-Expires=60&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEKf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIQCMhZ6r%2BEjJKQ%2Bs%2FjCR30%2B0djGU62uzddnaxQdSffBE%2BQIga33Re7bJvsJPnXtHN1BnRVHHGwFPuNskEpNOu7k9KMsqqwIIMBADGgwwNDU0NjY4MDY1NTYiDDZc2RAlXE9MJXqF7iqIAuUT2Rd9C4YT4bgdhiktvfp%2FvC%2B8sXI9g3aOKiUiqea5NggL8qMVh83qg3k7P%2FonRbdQ1In6%2FDekrhdHWDQhR2Nn18WAPh0bE7eDFxOwWmZBb3QZihROjfGNRiDl30JxeDlsZHmAhivR9uoLtsElX71ekFeDwh2yb6tjEHtXPBcK%2BRDwp59uENNBr0sdyg6W3zCifsgyZ2n98rOwLMFgvN9nUBM2sRvBUTCUeEcFYi03GaExPbyNkN7RAf1vYU1nxVK%2BFaoVbohXuG8UQwBIYMmhOPbMPWV602lmsIF95yAZVqTpAbwodSpzdKK6x%2Bbic3aGIaf3relHVLYBBvvF4bfRHu%2BDxjoWozDkneKyBjqdAX77znbdL7JRyBZHlEwX2M9s9bMgWyqLRgPiFRjaD%2FNL53YXjFt1vh0iADljGL%2BH%2BhewHPqQmWFw%2FRC2h7HK1A7EW4NVpagbIV2oXa5yGl8SCOc9EY1BNcE4bqZSVs0KcBr6UjE7ZcR%2BR2%2BTPCrUfvzBzJGXnEGYCFGwvyOgByLakVbdnu3%2BkydvhZZ0ke51nWS%2F6jYX824xWIB2sQ8%3D&X-Amz-SignedHeaders=host&x-id=GetObject&X-Amz-Signature=b0e177b4e6bc158018e386c28e34f4ff13a795db7fac55c75224af70b4d7b0f7).
What can be done is to wait until confirm button is clicked and then
disappears, which will bring us to next final success page, where the
test is looking for "ok" button.

Few improvements are also added to make sure the elements are found,
clicked, and next frame is rendered before we try to click any button.


<img width="459" alt="截屏2024-05-30 15 47 46"
src="https://github.com/MetaMask/metamask-extension/assets/12678455/4c7cfc4e-e0a2-4321-81ed-9753e49e001a">



<!--
Write a short description of the changes included in this pull request,
also include relevant motivation and context. Have in mind the following
questions:
1. What is the reason for the change?
2. What is the improvement/solution?
-->

[![Open in GitHub
Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/MetaMask/metamask-extension/pull/24908?quickstart=1)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

<!-- If applicable, add screenshots and/or recordings to visualize the
before and after of your change. -->

### **Before**

<!-- [screenshots/recordings] -->

### **After**

<!-- [screenshots/recordings] -->

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding
Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.

Co-authored-by: Harika Jetpoluru <153644847+hjetpoluru@users.noreply.github.com>
Co-authored-by: legobeat <109787230+legobeat@users.noreply.github.com>